# Generated by Django 5.0.6 on 2024-12-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='uploads')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
